name: Build ImmortalWrt

on:
    workflow_dispatch:

env:
    CLONE_COMMAND: git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git
    REPO_NAME: immortalwrt-mt798x

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Clone immortalwrtARM repo
              run: |
                  $CLONE_COMMAND

            - name: Copy config to source code
              run: |
                  cp -f .config feeds.conf.default diy.sh $REPO_NAME/

            - name: Install the software packages required for compilation
              run: |
                  sudo apt update && sudo apt upgrade -y
                  sudo apt-get install -y build-essential libssl-dev libz-dev wget

            - name: Set up ccache
              run: |
                  sudo apt-get install -y ccache
                  export CCACHE_DIR=$HOME/.ccache
                  echo "export CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
                  ccache --max-size=5G
                  export PATH="/usr/lib/ccache:$PATH"
                  echo "export PATH=/usr/lib/ccache:$PATH" >> $GITHUB_ENV
                  ccache -s

            - name: Download and install GCC 8
              run: |
                  wget http://ftp.us.debian.org/debian/pool/main/g/gcc-8/gcc-8-base_8.4.0-3_amd64.deb
                  wget http://ftp.us.debian.org/debian/pool/main/g/gcc-8/gcc-8_8.4.0-3_amd64.deb
                  wget http://ftp.us.debian.org/debian/pool/main/g/gcc-8/g++-8_8.4.0-3_amd64.deb
                  sudo dpkg -i gcc-8-base_8.4.0-3_amd64.deb gcc-8_8.4.0-3_amd64.deb g++-8_8.4.0-3_amd64.deb
                  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 80
                  sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 80
                  sudo update-alternatives --set gcc /usr/bin/gcc-8
                  sudo update-alternatives --set g++ /usr/bin/g++-8
                  gcc --version
                  g++ --version

            - name: Modify .config for ccache and GCC version
              run: |
                  echo "CONFIG_CCACHE=y" >> $REPO_NAME/.config
                  echo "CONFIG_SDK_GCC_VERSION=\"8.x\"" >> $REPO_NAME/.config

            - name: Get the dependency of immortalwrtARM
              run: |
                  cd $REPO_NAME
                  chmod +x diy.sh
                  ./diy.sh
                  ./scripts/feeds update -a && ./scripts/feeds install -a

            - name: Upload config before build
              uses: actions/upload-artifact@v3
              with:
                  name: config before build
                  path: .config

            - name: Build immortalwrtARM
              run: |
                  cd $REPO_NAME
                  make defconfig
                  make -j$(nproc) CC="ccache gcc" CXX="ccache g++"
                  pwd
                  ls
# 默认make -j$(nproc)，代表多线程编译。如果求稳想看报错信息，可以使用make -j1 V=99代替

            - name: Move results to root
              run: |
                  cd /home/runner/work/Actions-ImmortalWrt/Actions-ImmortalWrt/$REPO_NAME
                  mv bin/targets ../
                  cd ..

            - name: Upload build
              uses: actions/upload-artifact@v3
              with:
                  name: ImmortalWrt_build_files
                  path: targets
